# Generated by Django 4.2.2 on 2026-02-23 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='social_facebook',
            new_name='sacial_github',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='social_github',
            new_name='sacial_instagram',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='social_instagram',
            new_name='sacial_linkedin',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='social_youtube',
            new_name='sacial_youtube',
        ),
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='profile/defult_profile.webp', upload_to='profiles_user'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
